<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Models\yolo11n.onnx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Models\yolo11n.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="YoloSharp" Version="6.1.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisionFlow.Core\VisionFlow.Core.csproj" />
    <ProjectReference Include="..\VisionFlow.Hardware\VisionFlow.Hardware.csproj" />
  </ItemGroup>

</Project>
